name: Auto Approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@24ec4c8cc344fe1cdde70ff37e55ace9e848a1d8  # v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: |
          (
            github.event.pull_request.user.login == 'dependabot[bot]' ||
            github.event.pull_request.user.login == 'dependabot' ||
            github.event.pull_request.user.login == 'dependabot-preview[bot]' ||
            github.event.pull_request.user.login == 'dependabot-preview' ||
            github.event.pull_request.user.login == 'renovate[bot]' ||
            github.event.pull_request.user.login == 'renovate' ||
            github.event.pull_request.user.login == 'github-actions[bot]'
          )
            &&
          (
            github.actor == 'dependabot[bot]' ||
            github.actor == 'dependabot' ||
            github.actor == 'dependabot-preview[bot]' ||
            github.actor == 'dependabot-preview' ||
            github.actor == 'renovate[bot]' ||
            github.actor == 'renovate' ||
            github.actor == 'github-actions[bot]'
          )
